name: Release

on:
  push:
    tags:
        - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
            - build: windows
              os: windows-2022
              target: windows-x86_64
            - build: macos
              os: macos-13
              target: macos-x86_64
            - build: macos
              os: macos-14
              target: macos-arm64
            - build: ubuntu
              os: ubuntu-22.04
              target: ubuntu-x86_64

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
    
      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: |
            pip install -r requirements.txt pyinstaller
            pyinstaller -y -p ./app/ ./app/main.py
      - name: Archive
        shell: bash
        run: |
          target_file="ok_service_plugin_rembg-${{ env.VERSION }}-${{ matrix.target }}"
          7z a $target_file.zip ./dist/main/*
          echo "ASSET=$target_file.zip" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}